name: Build & Publish CentralDashboard-Angular Docker image
on:
  push:
    branches:
      - fix-katib-ui-tests-copy
      - master
      - v*-branch

env:
  DOCKER_USER: tariqhasan
  IMG: tariqhasan/centraldashboard-angular

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: tariqhasan
        password: -X5h!kEXZP-.sq*

    - name: Run CentralDashboard-Angular build/push
      run: |
        cd components/centraldashboard-angular
        make docker-build docker-push
    
    - name: Run CentralDashboard-Angular build/push latest
      run: |
        export TAG=latest
        cd components/centraldashboard-angular
        make docker-build docker-push

    - name: Run CentralDashboard-Angular build/push on Version change
      id: version
      if: steps.filter.outputs.version == 'true'
      run: |
        export TAG=$(cat releasing/version/VERSION)
        cd components/centraldashboard-angular
        make docker-build docker-push
